apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: PathPrefix()
      priority: 10
      services:
        - name: guestbook-ui
          port: 80