apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: ClientIP(`0.0.0.0/0`)
      priority: 10
      services:
        - name: guestbook-ui
          port: 80
  tls:
    certResolver: default