apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/demo`)
      middlewares:
        - name: demo-stripprefix
      priority: 10
      services:
        - name: guestbook-ui
          port: 80
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: demo-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /demo